// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swuqtxsrwoiquwdfupas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dXF0eHNyd29pcXV3ZGZ1cGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mjc4NzksImV4cCI6MjA2NzAwMzg3OX0.OQrpKmqiZI8__paLxP3SnJP7yHx2dIlaATTOPSRFRhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});